env:
  es6: true # 対応環境をES6に
rules:
  # Rule一覧:https://eslint.org/docs/latest/rules/
  # TODO:importの順番をアルファベット順 or Reactは上にして残りはアルファベット順
  # ESLintが作成したルールの種類（https://eslint.org/docs/latest/rules/）
  # Possible Problems
  no-unused-vars: # 未使用変数の検知
    [
      error,
      {
        vars: all, # デフォルト（よくわからん）
        varsIgnorePattern: "[iI]gnored|^_", #未使用変数の検知を無視する指定（正規表現）
        # args: after-used, # チェックする変数の数
        args: after-used, # チェックする変数の数(all,after-used,none)
        argsIgnorePattern: ^_,
        caughtErrors: all, # try-catch文のcatchのエラー未使用チェック
        # caughtErrorsIgnore: "",
        destructuredArrayIgnorePattern: ^_,
        ignoreRestSiblings: false,
      },
    ]

  # Suggestions（）
  no-console: 0 # console.logの設定（0は許可）
  eqeqeq: [error, always] # ===の強制
  curly: [error, multi, consistent] # if文などの中身が２行以上ある時にのみ警告を出す if(condition) return true などは許される
  no-alert: [error] # フロントのalert文を使わない
  camelcase: # 変数名をキャメルケースにする
    [
      error,
      {
        properties: always, # デフォルト設定
      },
    ]
  func-style: [error, declaration, { allowArrowFunctions: true }]
  logical-assignment-operators: [error, always]
  # Layout & Formatting（これらのルールは、コードがどのように実行されるかよりも、コードがどのように見えるかを気にします。）
  semi: [error, always] # 文末のセミコロン
  quotes: [error, double, { allowTemplateLiterals: true }] #ダブルクオートとテンプレートリテラルを使えるようにする
  no-var: [error] # varは許可しない。let,constのみ。 --fixでvarをletに変更できる
  no-magic-numbers: [error, { ignore: [1] }] # マジックナンバーの不許可 ignoreで無視できる数を定義できる array.length-1とかはよく使うから1だけ無視するとか
  no-nested-ternary: [error] # ネストされた３項演算子を許可しない
  no-param-reassign: [
      error,
      {
        props: true, # bar.item = "change"とかも許さない。デフォはfalse
        ignorePropertyModificationsFor: ["hoge"], # hoge.item = "change"は許す
        ignorePropertyModificationsForRegex: ["^bar"], # 変更を許可する値を正規表現で書く
      },
    ]
  one-var: [
      error,
      never,
      {
        var: always, # var:変数宣言は1つのスコープで１回だけ
        let: never, # let:変数宣言は1つのスコープで何回でも
        const: consecutive, # const: 変数宣言は1つのスコープで何回でもOKやけど連続した変数宣言は1つにまとめる
      },
    ]

parserOptions:
  #   ecmaVersion: 6 # constとか``を使えるようにする
  #   # ecmaVersion: "latest"
  sourceType: module # export importを使えるようにする
  ecmaFeatures:
    impliedStrict: true # strict modeを有効にする
    # jsx: true # これでJSXの構文もフォローできるけどReactを使う場合はeslint-plugin-reactを使うべきとドキュメントに書いてある
noInlineConfig: false # インラインで書いたルールをすべて無効化する（厳しいからTrueにすることはなさそう）
reportUnusedDisableDirectives: true # 未使用のeslint-disableコメントがあれば通知する
