rules:
  semi: ["error", "always"] # 文末のセミコロン
  quotes: ["error", "double", { "allowTemplateLiterals": true }] #ダブルクオートとテンプレートリテラルを使えるようにする
  no-console: [0]
parserOptions:
  ecmaVersion: 6 # constとか``を使えるようにする
  # ecmaVersion: "latest"
  sourceType: "module" # export importを使えるようにする
